name: "SARIF upload"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Get Contrast SARIF
        uses: Contrast-Security-OSS/contrast-sca-action@v2
        with:
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          apiUrl: https://apptwo.contrastsecurity.com
          applicationId: 48df5e8b-8bf4-4179-b95e-5ff6da916d90
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          command: sarif
          #ghasEnabled: false
          #metadata: sessionMetadataKey1=value,key2=value...
          orgId: 9eb886b2-2cc8-4476-be35-d9fae474c47f
