name: "SARIF upload"

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every Wednesday at 15:45 UTC.
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Contrast SCA Action
        uses: Contrast-Security-OSS/contrast-sca-action@v2
        with:
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          orgId: 9eb886b2-2cc8-4476-be35-d9fae474c47f
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          apiUrl: https://apptwo.contrastsecurity.com
          applicationId: 48df5e8b-8bf4-4179-b95e-5ff6da916d90
          #filePath: .
          #severity: medium
          command: sarif
