name: "SARIF upload"

on:
  workflow_dispatch:

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Get Contrast SARIF
        uses: andersonshatch/contrast-sarif-action@d0c3fc64f4dfd7c3c1b86026cef590b12fd9b2ea
        with:
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          apiUrl: ${{ secrets.CONTRAST_API_URL }}
          applicationId: 9464c8c8-4b6b-46db-bff7-4da505efe960
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          command: sarif
          #ghasEnabled: false
          #metadata: sessionMetadataKey1=value,key2=value...
          orgId: ${{ secrets.CONTRAST_ORG_ID }}
